### ISSUE TITLE
Migrate People not Poaching site

### ISSUE THREAD

**Issue by stephen-cox** [IIED-org/d8a1#157]
www.peoplenotpoaching.org
https://prod.peoplenotpoaching.org

- [x] Test prod site
- [x] Set TTLs to 5 mins
- [x] Merge and deploy #158 
- [x] Content freeze - readonlymode?
- [x] Migrate db & files
- [x] Test
- [x] Remove basic authentication
- [x] Update DNS etc.
- [x] Regenerate SSL certificate
- [x] Test

Launch target: 20241008T11:00

**Comment by stephen-cox** [comment]
The changes needed to move this site are in PR https://github.com/IIED-org/d8a1/pull/158

**Comment by stephen-cox** [comment]
@cbrody This site is now setup on the new server for testing here: https://prod.peoplenotpoaching.org/

Please take a look at let me know if you find anything that's not working as expected.

**Comment by cbrody** [comment]
Thanks @stephen-cox, https://prod.peoplenotpoaching.org/explore (searchAPI-based view containing a leaflet map) is currently 404, otherwise looks good so far...

**Comment by stephen-cox** [comment]
> [https://prod.peoplenotpoaching.org/explore](https://prod.peoplenotpoaching.org/explore) (searchAPI-based view containing a leaflet map) is currently 404

@cbrody This page should be working for logged out users now

**Comment by cbrody** [comment]
Site successfully migrated at 20241008T15:45
